### ISSUE TITLE
Feedback on theme design

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress-Themes#9]
See discussion starting here:  https://github.com/ClassicPress/ClassicPress-Themes/issues/9#issuecomment-437703242

---

Original message for this issue (code has since been committed to the repo):

[classicpress-susty-child-tk2.zip](https://github.com/ClassicPress/ClassicPress-Themes/files/2568989/classicpress-susty-child-tk2.zip)

**Comment by KTS915** [comment]
Please note that the latest version relies on the WP/CP template hierarchy. To make it function as intended, you need to do the following:

1. Create and publish two posts, called Home and Blog. (There is no need to select a particular template because the following steps will override that anyway.)
2. Go to `Settings -> Reading` and, for `Your homepage displays`, select `A static page`.
3. For `Homepage`, choose Home.
4. For `Posts Page`, choose Blog.
5. For `Blog pages show at most` select a number that is divisible by 6. I suggest either 6 or 12. (This is to ensure that the blog posts page looks its best, irrespective of whether the width of the device screen accommodates a one-, two-, or three-column view.)
6. Hit `Save Changes`.

Note that `front-page.php` governs the home/front page, while `home.php` governs the blog page. (I don't understand it either, but that's how it works.)

Finally, following discussions on Slack, I have included live search functionality (using the REST API and jQuery UI Autocomplete) in the theme in lines 65-99 of `functions.php` and in `/js/search.js`. I have added the appropriate nonce, but please feel free to audit the code for security or any other reason.

**Comment by striebwj** [comment]
@KTS915 Looks good, thank you! 🙂 I have pushed the changes to the repo and referenced this issue for the future. I will also upload this to the beta site so we can start testing it.

**Comment by BlueSkyPhoenix** [comment]
This is a great start, thanks to @KTS915 for the great work.

@striebwj  & @nylen , my suggestions for revisions to the beta.classicpress.net theme:

- In the main menu, the hover state is currently `color: #040402; background: #fff;`. The right side of some of the menu items is cut off; also, the down arrow is hidden in the hover state. I propose we change the background to #006b81 (to maintain A11y) and keep the text white; I don't know how properly to represent via code how to fix the problem of the area being cut off on the right but hopefully you can see what needs to be done in the screenshot below:
![screen shot 2018-11-11 at 3 01 37 pm](https://user-images.githubusercontent.com/14037041/48317626-bf422780-e5c2-11e8-8985-1e92ba576d8c.jpg)

I would extend this hover state to all menu items, rather than have hover be white.

- For all menu items and the search area; the height seems excessive. Is there a way to tighten this up? 

- Having a color change plus the glow on the hover state appears jarring; can we just have the color change? I like the change to the darker purple (and it meets a11y requirements) 
![screen shot 2018-11-11 at 3 07 22 pm](https://user-images.githubusercontent.com/14037041/48317680-a128f700-e5c3-11e8-9458-83e6556ef8d4.jpg)

- On the yellow buttons, I suggest the text remain dark and remove the white glow.

- On the aqua buttons, I suggest removing the glow effect.

As some have already offered negative feedback on the button gradients, we may choose to remove gradients on all buttons and instead use the lighter / darker shades indicated in the design spec to indicate state changes.

- The "Community First" area had a feather in the background to carry through some of the branding farther down the home page; I am attaching an SVG if you'd like to add it.
[gray-background-feather.svg.zip](https://github.com/ClassicPress/ClassicPress-Themes/files/2569783/gray-background-feather.svg.zip)

- In the comp and on the stylesheet, I'd indicated semi-bold throughout for H class, but this appears to perhaps be bold? Can we check this? It appears heavy to me. 

- Is underlining necessary for links? (I see this in the footer). I'd prefer to see another hover indicator -- perhaps flipping to the opposite color on hover instead? aqua>purple or purple>aqua. There is also underlining happening on hover of the social media icons.

- When hovering over our logo, a box with a dotted line appears. Can we remove that?

- In the footer and just above, was it intentional to use both "Made with <3 with ClassicPress" and "Proudly powered by ClassicPress" ? And, was it intentional that "Proudly powered by ClassicPress" be a link, but not be purple like the other links?

- We may want to add a Slack icon next to the Github and Twitter icons. Do we want to list any other social media accounts?

Thank you.

**Comment by KTS915** [comment]
@BlueSkyPhoenix @nylen @striebwj I'll look more closely at all these suggestions but, please, do not remove the glow. A11y specs are very clear that mere changes of color are insufficient to indicate focus. That's why the default is outline. But on such large buttons, outline doesn't work well at all. The glow effect has been taken from a plugin I've worked on, and I know it works really well.

**Comment by KTS915** [comment]
The same point applies to underline on links. Mere changes of color do not comply with a11y specs. A11y is not just about contrast. There are many visual issues for which a11y is designed to cater. So there has to be an added visual clue apart from any change of color. 

I can also confirm that the font weight for headings is set at 600, which is semi-bold.

I would agree with adding other social icons as desired. Much of the reason for placing them where I did is that there is then plenty of space to add more alongside.

One last point. @BlueSkyPhoenix comments about some items being tall. That's true. But it's also built in to the Susty theme, which is very much designed to meet a11y specs. Making stuff tall like that makes it so much easier for people who otherwise struggle to read the screen. I would suggest talking to fwolf about this, because not only was it he who suggested using Susty (a very good idea, in my opinion) but he also has the very sort of limited eyesight that benefits from what Susty provides.

**Comment by senlin** [comment]
The official Facebook page is https://www.facebook.com/GetClassicPress/
LinkedIn: https://www.linkedin.com/company/classicpress/

**Comment by BlueSkyPhoenix** [comment]
@KTS915 thanks for your feedback; I am not an expert on a11y and that's why I asked about underlining. 
I personally find the glow to be jarring, especially the purple, but defer to others here on final decisions. 
If we are going to keep the glow, then I would remove the gradients on the buttons. It feels like too much to me. 
My comment on menu items being "tall" is referring to the padding around the menu item; perhaps once the padding/cut off issues are fixed on the right it will appear more balanced. I would also encourage whoever is making the changes to watch the padding on the topmost submenu item, it would be nice to see it match the bottom padding on the bottom-most submenu item, rather than butted up against the top. 
![screen shot 2018-11-11 at 4 22 03 pm](https://user-images.githubusercontent.com/14037041/48318386-0bdf3000-e5ce-11e8-8e96-14d4aa994790.jpg)

**Comment by KTS915** [comment]
@BlueSkyPhoenix We can certainly get rid of the padding around the menu items, especially if the background color is changed. I added it because, if the background is white, then it merges into the main page when a submenu is open. I thought you were were referring to the menu items themselves. If not, I apologize for misunderstanding.

As for the glow, what might be possible is to reduce its width, say changing from `box-shadow: 0 0 6px 4px` to `box-shadow: 0 0 3px 2px`.

**Comment by nylen** [comment]
I'm reopening this one because there are multiple suggestions left to discuss and address.

**Comment by KTS915** [comment]
I can now see what @BlueSkyPhoenix means about the right side of the some of the menu items getting cut off. I tested this on Firefox, where it works fine, but I see that the cut-offs do happen on Chrome. Weird. I will investigate.

As for the down arrows not showing on hover, that's deliberate. The arrows exist to indicate that there is a sub-menu. When a user hovers over on focuses on a menu item with a submenu, that submenu opens. There is then no reason to display the down arrow. (If we were to display anything, it should really be an up arrow, but that would be wrong too because clicking on it wouldn't close the submenu.) So this means that appropriate indications are provided when they should be, and not when they shouldn't be.

**Comment by nylen** [comment]
I also think the down arrow should show in black on hover.  Having it disappear looks wrong to me, and the logic is debatable.

> The arrows exist to indicate that there is a sub-menu.

Exactly: the submenu still exists (under the parent menu item, hence the arrow pointing down) even when it is hovered.

Also, in the following state (a child item of a submenu is hovered), the arrow is still shown:

<img src="https://user-images.githubusercontent.com/227022/48326853-95f8ba00-e609-11e8-9969-58ec74ee8378.png" width="350">

**Comment by KTS915** [comment]
>the logic is debatable.

You mean you don't agree!

**Comment by KTS915** [comment]
OK, we can get the menu buttons to work properly without being cut off by using flexbox.

So at line 330 in `styles.css`, the relevant code should now be:
	`.menu li a {
		display: flex;
		flex-grow: 1;
		padding: 1.5em;
	}`

Then we need to adjust the arrows a few lines down to this:
	`.menu-item-has-children > a:after {
		content: '';
		border: 6px solid transparent;
		border-top: 6px solid #fff;
		margin-top: 0.65em;
		margin-left: 8px;
		display: inline-block;
		vertical-align: middle;
	}`

**Comment by nylen** [comment]
I've committed these changes in 8b2fb7c.

**Comment by KTS915** [comment]
To get the arrow to change to black on hover, add this:
	`.menu-item-has-children > a:hover:after {
		border-top: 6px solid #040402;
	}`

**Comment by nylen** [comment]
Ok, I created https://github.com/ClassicPress/ClassicPress-Themes/pull/18 with that individual change so that we can decide whether it's something we want to do.

**Comment by KTS915** [comment]
Actually, you convinced me when you pointed out that the arrow still shows when the submenu is open and the hover of focus is on a submenu item!

**Comment by nylen** [comment]
We shouldn't remove the glow on the buttons (see longer explanation [on the forums](https://forums.classicpress.net/t/on-accessibility-and-hover-styles/87)) but we've made it a bit smaller.

> When hovering over our logo, a box with a dotted line appears. Can we remove that?

Yes - I think we can come up with a better hover effect here.

> In the comp and on the stylesheet, I'd indicated semi-bold throughout for H class, but this appears to perhaps be bold? Can we check this? It appears heavy to me.

This still needs to be done, I think.

> There is also underlining happening on hover of the social media icons.
> We may want to add a Slack icon next to the Github and Twitter icons. Do we want to list any other social media accounts?

The social media icons need some further work.  I'd like to see SVGs of all the same style (like the logo inside a white circle for example).  I opened #17 for the GitHub icon specifically but they have changed again since I opened that one.

We can also clean up the hover style, adding something that looks good and is accessible.  Having all the images in SVG format will make this easy to do.

---

With that, I think most of the feedback from the discussion above is either fixed (on https://test.classicpress.net) or has a response.

**Is there anything I missed?**

If these remaining to-do items stick around throughout the week, it will be better to split what remains out into separate issues and close this one.  That way we can focus on one task at a time, and "cross things off the list" as they are done, so to speak.

**Comment by senlin** [comment]
Apart from Twitter we also are on Facebook (https://www.facebook.com/GetClassicPress/) and LinkedIn (https://www.linkedin.com/company/classicpress/). I think they should be aded too there.

**Comment by striebwj** [comment]
Just submitted a 2 PRs ( #21 & #22 ) with svg icons. I am also in the process of finding svg icons with rounded backgrounds as discussed above.

**Comment by nylen** [comment]
I think #21 is good.  Thanks for putting those together.

**Comment by nylen** [comment]
Closing, we are live with this theme (and some modifications) at https://www-new.classicpress.net .  Report further specific issues at https://github.com/ClassicPress/ClassicPress-Network/issues
